language: php
sudo: required
dist: trusty

php:
- 7.2

services:
  -mysql
addons:
  chrome: stable

install:
- cp .env.testing .env
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- php artisan key:generate

before_script:
- mysql -c 'create database testing;' U -mysql
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- php artisan serve &



script:
- phpunit
- php artisan dusk
